package hu.szte.battery.computetask.Battery.ComputeTask.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "RunTime")
public class RunTime {
  private String id;
  private long ms;
  private LocalDateTime date;
  private boolean local;

  public RunTime() {}

  public RunTime(long ms, LocalDateTime date, boolean local) {
    this.ms = ms;
    this.date = date;
    this.local = local;
  }

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  @DynamoDBAttribute
  public long getMs() {
    return ms;
  }

  public void setMs(long ms) {
    this.ms = ms;
  }

  @DynamoDBAttribute
  public LocalDateTime getDate() {
    return date;
  }

  public void setDate(LocalDateTime date) {
    this.date = date;
  }

  @DynamoDBAttribute
  public boolean isLocal() {
    return local;
  }

  public void setLocal(boolean local) {
    this.local = local;
  }
}
